using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Persona_5_Real_Time_Editor
{
    public partial class SelectionForm : Form
    {
		//The final selection string
        public string Selection;
		//A bool used to check whether the selection has been confirmed
        public bool HasConfirmedSelection;
		
		//Var used to decide whether to load personas or skills form data
        private static string FormType;
		//Bool used to check whether the search has changed (may not be needed..?)
        private static bool SearchChanged;
		//Where the lisbox data is stored
        private static List<object> TrueCollection, LastCollection;
		
        private void searchButton_Click(object sender, EventArgs e)
        {
            string search = searchInput.Text;
            List<object> curCollection = new List<object>();

            if (search != "")
            {
                //Go through LastCollection and add potential searches to curCollection
                foreach (object item in LastCollection)
                {
                    if (item.ToString().Contains(search, StringComparison.InvariantCultureIgnoreCase))
                        curCollection.Add(item);
                }
            }
            else
                curCollection = TrueCollection;

            //Clear personaList and fill it with curCollection
            listBox.Items.Clear();
            foreach (object item in curCollection)
                listBox.Items.Add(item);
            //Set LastCollection as curCollection
            LastCollection = curCollection;
        }

        private void confirmButton_Click(object sender, EventArgs e)
        {
            if (listBox.SelectedItem != null)
            {
                Selection = listBox.SelectedItem.ToString();
                Selection = Selection.Remove(0, Selection.Length - 4);
                HasConfirmedSelection = true;
                Close();
            }
            else
                MessageBox.Show("Please select an entry from the list!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }

        public SelectionForm(string formType)
        {
            FormType = formType;

            Selection = "XXXX";
            SearchChanged = false;
            HasConfirmedSelection = false;
            TrueCollection = new List<object>();
            LastCollection = new List<object>();

            InitializeComponent();
        }

        private void SelectionForm_Load(object sender, EventArgs e)
        {
            Text = FormType + " Selection";
            searchLabel.Text = "Search for " + FormType;

            listBox.Items.Clear();
            if(FormType == "Persona")
            {
                TrueCollection.Add("Metatron ; 0001");
                TrueCollection.Add("Beelzebub ; 0002");
                TrueCollection.Add("Cu Chulainn ; 0003");
                TrueCollection.Add("Jack-o'-Lantern ; 0004");
                TrueCollection.Add("Jack Frost ; 0005");
                TrueCollection.Add("Pixie ; 0006");
                TrueCollection.Add("Cerberus ; 0007");
                TrueCollection.Add("Lilim ; 0008");
                TrueCollection.Add("Eligor ; 0009");
                TrueCollection.Add("Odin ; 000A");
                TrueCollection.Add("Hua Po ; 000B");
                TrueCollection.Add("Decarabia ; 000C");
                TrueCollection.Add("Mara ; 000D");
                TrueCollection.Add("Ose ; 000E");
                TrueCollection.Add("Thor ; 000F");
                TrueCollection.Add("Unicorn ; 0010");
                TrueCollection.Add("Uriel ; 0011");
                TrueCollection.Add("Sarasvati ; 0012");
                TrueCollection.Add("Valkyrie ; 0013");
                TrueCollection.Add("Yaksini ; 0014");
                TrueCollection.Add("Ganesha ; 0015");
                TrueCollection.Add("Anubis ; 0016");
                TrueCollection.Add("Mot ; 0017");
                TrueCollection.Add("Raphael ; 0018");
                TrueCollection.Add("Scathach ; 0019");
                TrueCollection.Add("High Pixie ; 001A");
                TrueCollection.Add("Barong ; 001B");
                TrueCollection.Add("Girimehkala ; 001C");
                TrueCollection.Add("King Frost ; 001D");
                TrueCollection.Add("Narcissus ; 001E");
                TrueCollection.Add("Isis ; 001F");
                TrueCollection.Add("Lamia ; 0020");
                TrueCollection.Add("Legion ; 0021");
                TrueCollection.Add("Rakshasa ; 0022");
                TrueCollection.Add("Mokoi ; 0023");
                TrueCollection.Add("Forneus ; 0024");
                TrueCollection.Add("Setanta ; 0025");
                TrueCollection.Add("Titania ; 0026");
                TrueCollection.Add("Incubus ; 0027");
                TrueCollection.Add("Oni ; 0028");
                TrueCollection.Add("Lilith ; 0029");
                TrueCollection.Add("Rangda ; 002A");
                TrueCollection.Add("Makami ; 002B");
                TrueCollection.Add("Parvati ; 002C");
                TrueCollection.Add("Gabriel ; 002D");
                TrueCollection.Add("Zaou-Gongen ; 002E");
                TrueCollection.Add("Alice ; 002F");
                TrueCollection.Add("Kali ; 0030");
                TrueCollection.Add("Kurama Tengu ; 0031");
                TrueCollection.Add("Oberon ; 0032");
                TrueCollection.Add("Shiki-Ouji ; 0033");
                TrueCollection.Add("Yamata-no-Orochi ; 0034");
                TrueCollection.Add("Orobas ; 0035");
                TrueCollection.Add("Hanuman ; 0036");
                TrueCollection.Add("Archangel ; 0037");
                TrueCollection.Add("Obariyon ; 0038");
                TrueCollection.Add("Queen Mab ; 0039");
                TrueCollection.Add("Sandalphon ; 003A");
                TrueCollection.Add("Abaddon ; 003B");
                TrueCollection.Add("Shiisaa ; 003C");
                TrueCollection.Add("Belial ; 003E");
                TrueCollection.Add("Leanan Sidhe ; 003F");
                TrueCollection.Add("Cybele ; 0040");
                TrueCollection.Add("Chernobog ; 0041");
                TrueCollection.Add("Flauros ; 0042");
                TrueCollection.Add("Ippon-Datara ; 0043");
                TrueCollection.Add("Orthrus ; 0044");
                TrueCollection.Add("Succubus ; 0045");
                TrueCollection.Add("Mothman ; 0046");
                TrueCollection.Add("Dominion ; 0048");
                TrueCollection.Add("Nekomata ; 0049");
                TrueCollection.Add("Black Frost ; 004A");
                TrueCollection.Add("Arahabaki ; 004B");
                TrueCollection.Add("Angel ; 004C");
                TrueCollection.Add("Skadi ; 004D");
                TrueCollection.Add("Kikuri-Hime ; 004E");
                TrueCollection.Add("Chi You ; 004F");
                TrueCollection.Add("Power ; 0050");
                TrueCollection.Add("Inugami ; 0051");
                TrueCollection.Add("Nebiros ; 0052");
                TrueCollection.Add("Slime ; 0054");
                TrueCollection.Add("Anzu ; 0055");
                TrueCollection.Add("Yatagarasu ; 0056");
                TrueCollection.Add("Yoshitsune ; 0057");
                TrueCollection.Add("Take-Minakata ; 0058");
                TrueCollection.Add("Ame-no-Uzume ; 0059");
                TrueCollection.Add("Kushinada ; 005A");
                TrueCollection.Add("Kumbhanda ; 005B");
                TrueCollection.Add("Ongyo-Ki ; 005C");
                TrueCollection.Add("Kin-Ki ; 005D");
                TrueCollection.Add("Sui-Ki ; 005E");
                TrueCollection.Add("Fuu-Ki ; 005F");
                TrueCollection.Add("Jatayu ; 0060");
                TrueCollection.Add("Kaiwan ; 0061");
                TrueCollection.Add("Kelpie ; 0062");
                TrueCollection.Add("Thoth ; 0063");
                TrueCollection.Add("Dionysus ; 0064");
                TrueCollection.Add("Asparas ; 0065");
                TrueCollection.Add("Andras ; 0065");
                TrueCollection.Add("Koropokguru ; 0068");
                TrueCollection.Add("Koppa Tengu ; 0069");
                TrueCollection.Add("Regent (Treasure) ; 006A");
                TrueCollection.Add("Queen's Necklace (Treasure) ; 006B");
                TrueCollection.Add("Stone of Scone (Treasure) ; 006C");
                TrueCollection.Add("Koh-i-Noor (Treasure) ; 006D");
                TrueCollection.Add("Orlov (Treasure) ; 006E");
                TrueCollection.Add("Emperor's Amulet (Treasure) ; 006F");
                TrueCollection.Add("Hope Diamond (Treasure) ; 0070");
                TrueCollection.Add("Crystal Skull (Treasure) ; 0071");
                TrueCollection.Add("Mandrake ; 0079");
                TrueCollection.Add("Baal ; 007A");
                TrueCollection.Add("Dakini ; 007B");
                TrueCollection.Add("Silky ; 007C");
                TrueCollection.Add("Bugs ; 007D");
                TrueCollection.Add("Black Ooze ; 007E");
                TrueCollection.Add("Bicorn ; 007F");
                TrueCollection.Add("Mithras ; 0080");
                TrueCollection.Add("Sudama ; 0081");
                TrueCollection.Add("Kodama ; 0082");
                TrueCollection.Add("Agathion ; 0083");
                TrueCollection.Add("Onmoraki ; 0084");
                TrueCollection.Add("Nue ; 0085");
                TrueCollection.Add("Pisaca ; 0086");
                TrueCollection.Add("Melchizedek ; 0087");
                TrueCollection.Add("Baphomet ; 0088");
                TrueCollection.Add("Raja Naga ; 0089");
                TrueCollection.Add("Naga ; 008A");
                TrueCollection.Add("Garuda ; 008B");
                TrueCollection.Add("Moloch ; 008C");
                TrueCollection.Add("Norn ; 008D");
                TrueCollection.Add("Belphegor ; 008E");
                TrueCollection.Add("Berith ; 008F");
                TrueCollection.Add("Choronzon ; 0090");
                TrueCollection.Add("Nigi Mitama ; 0097");
                TrueCollection.Add("Kushi Mitama ; 0098");
                TrueCollection.Add("Ara Mitama ; 0099");
                TrueCollection.Add("Saki Mitama ; 009A");
                TrueCollection.Add("Shiva ; 009C");
                TrueCollection.Add("Michael ; 009D");
                TrueCollection.Add("Asura ; 009E");
                TrueCollection.Add("Mada ; 009F");
                TrueCollection.Add("Mother Harlot ; 00A0");
                TrueCollection.Add("Sandman ; 00A1");
                TrueCollection.Add("Lachesis ; 00A2");
                TrueCollection.Add("Atropos ; 00A3");
                TrueCollection.Add("Ardha ; 00A4");
                TrueCollection.Add("Vishnu ; 00A6");
                TrueCollection.Add("Hariti ; 00A7");
                TrueCollection.Add("Yurlungur ; 00A8");
                TrueCollection.Add("Hecatoncheires ; 00A9");
                TrueCollection.Add("Satanael ; 00AA");
                TrueCollection.Add("Orpheus ; 00B5");
                TrueCollection.Add("Thanatos ; 00B6");
                TrueCollection.Add("Izanagi ; 00B7");
                TrueCollection.Add("Magatsu Izanagi ; 00B8");
                TrueCollection.Add("Kaguya ; 00B9");
                TrueCollection.Add("Ariadne ; 00BA");
                TrueCollection.Add("Asterius ; 00BB");
                TrueCollection.Add("Tsukiyomi ; 00BC");
                TrueCollection.Add("Messiah ; 00BD");
                TrueCollection.Add("Messiah Picaro ; 00BE");
                TrueCollection.Add("Orpheus Picaro ; 00BF");
                TrueCollection.Add("Thanatos Picaro ; 00C0");
                TrueCollection.Add("Izanagi Picaro ; 00C1");
                TrueCollection.Add("Magatsu Izanagi Picaro ; 00C2");
                TrueCollection.Add("Kaguya Picaro ; 00C3");
                TrueCollection.Add("Ariadne Picaro ; 00C4");
                TrueCollection.Add("Asterius Picaro ; 00C5");
                TrueCollection.Add("Tsukiyomi Picaro ; 00C6");
                TrueCollection.Add("Arsene ; 00C9");
                TrueCollection.Add("Captain Kidd ; 00CA");
                TrueCollection.Add("Zorro ; 00CB");
                TrueCollection.Add("Carmen ; 00CC");
                TrueCollection.Add("Goemon ; 00CD");
                TrueCollection.Add("Johanna ; 00CE");
                TrueCollection.Add("Milady ; 00CF");
                TrueCollection.Add("Necronomicon ; 00D0");
                TrueCollection.Add("Robin Hood ; 00D1");
                TrueCollection.Add("Loki ; 00D2");
                TrueCollection.Add("Seiten Taisei ; 00D4");
                TrueCollection.Add("Satan ; 00FC");
                TrueCollection.Add("Lucifer ; 00FD");
                TrueCollection.Add("Kohryu ; 00FE");
                TrueCollection.Add("Okuninushi ; 00FF");
                TrueCollection.Add("Futsunushi ; 0103");
                TrueCollection.Add("Seth ; 0105");
                TrueCollection.Add("Ishtar ; 0106");
                TrueCollection.Add("Surt ; 0108");
                TrueCollection.Add("Siegfried ; 0109");
                TrueCollection.Add("Lakshmi ; 010A");
                TrueCollection.Add("Fortuna ; 0110");
                TrueCollection.Add("Suzaku ; 0111");
                TrueCollection.Add("Sieryu ; 0112");
                TrueCollection.Add("Genbu ; 0113");
                TrueCollection.Add("Byakko ; 0114");
                TrueCollection.Add("Bishamonten ; 0115");
                TrueCollection.Add("Koumokuten ; 0116");
                TrueCollection.Add("Jikokuten ; 0117");
                TrueCollection.Add("Zouchouten ; 0118");
                TrueCollection.Add("Hell Biker ; 0119");
                TrueCollection.Add("Daisoujou ; 011A");
                TrueCollection.Add("Trumpeter ; 011B");
                TrueCollection.Add("White Rider ; 011C");
                TrueCollection.Add("Matador ; 011D");
                TrueCollection.Add("Pale Rider ; 011E");
                TrueCollection.Add("Horus ; 011F");
                TrueCollection.Add("Attis ; 0121");
                TrueCollection.Add("Sraosha ; 0124");
                TrueCollection.Add("Mitra ; 0127");
                TrueCollection.Add("Phoenix ; 0128");
                TrueCollection.Add("Principality ; 0129");
                TrueCollection.Add("Neko Shogun ; 012A");
                TrueCollection.Add("Vasuki ; 012B");
                TrueCollection.Add("Ananta ; 012C");
                TrueCollection.Add("Throne ; 012D");
                TrueCollection.Add("Quetzalcoatl ; 012F");
                TrueCollection.Add("Red Rider ; 0130");
                TrueCollection.Add("Black Rider ; 0131");
                TrueCollection.Add("Pazuzu ; 0134");
            }
            else if(FormType == "Skill")
            {
                TrueCollection.Add("Agi ; 000A");
                TrueCollection.Add("Agilao ; 000B");
                TrueCollection.Add("Agydine ; 000C");
                TrueCollection.Add("Maragi ; 000D");
                TrueCollection.Add("Maragyon ; 000E");
                TrueCollection.Add("Maragidyne ; 000F");
                TrueCollection.Add("Agi ; 0010");
                TrueCollection.Add("Maragi ; 0011");
                TrueCollection.Add("Bufu ; 0014");
                TrueCollection.Add("Bufudyne ; 0015");
                TrueCollection.Add("Mabufu ; 0016");
                TrueCollection.Add("Mabufu ; 0017");
                TrueCollection.Add("Mabufula ; 0018");
                TrueCollection.Add("Mabufudyne ; 0019");
                TrueCollection.Add("Bufu ; 001A");
                TrueCollection.Add("Mabufu ; 001B");
                TrueCollection.Add("Garu ; 001E");
                TrueCollection.Add("Garula ; 001F");
                TrueCollection.Add("Garudyne ; 0020");
                TrueCollection.Add("Magaru ; 0021");
                TrueCollection.Add("Magarula ; 0022");
                TrueCollection.Add("Magarudyne ; 0023");
                TrueCollection.Add("Garu ; 0024");
                TrueCollection.Add("Zio ; 0028");
                TrueCollection.Add("Zionga ; 0029");
                TrueCollection.Add("Ziodyne ; 002A");
                TrueCollection.Add("Mazio ; 002B");
                TrueCollection.Add("Mazionga ; 002C");
                TrueCollection.Add("Maziodyne ; 002D");
                TrueCollection.Add("Zio ; 002E");
                TrueCollection.Add("Mazio ; 002F");
                TrueCollection.Add("Hama ; 0032");
                TrueCollection.Add("Hamaon ; 0033");
                TrueCollection.Add("Mahama ; 0034");
                TrueCollection.Add("Mahamaon ; 0035");
                TrueCollection.Add("Kouha ; 0036");
                TrueCollection.Add("Kouga ; 0037");
                TrueCollection.Add("Kougaon ; 0038");
                TrueCollection.Add("Makouha ; 0039");
                TrueCollection.Add("Makouga ; 003A");
                TrueCollection.Add("Makougaon ; 003B");
                TrueCollection.Add("Mudo ; 003C");
                TrueCollection.Add("Mamudo ; 003E");
                TrueCollection.Add("Mamudoon ; 003F");
                TrueCollection.Add("Eiha ; 0040");
                TrueCollection.Add("Eiga ; 0041");
                TrueCollection.Add("Eigaon ; 0042");
                TrueCollection.Add("Maeiha ; 0043");
                TrueCollection.Add("Maeiga ; 0044");
                TrueCollection.Add("Maeigaon ; 0045");
                TrueCollection.Add("Megido ; 0046");
                TrueCollection.Add("Megidola ; 0047");
                TrueCollection.Add("Megidolaon ; 0048");
                TrueCollection.Add("Frei ; 0049");
                TrueCollection.Add("Freila ; 004A");
                TrueCollection.Add("Freidyne ; 004B");
                TrueCollection.Add("Mafrei ; 004C");
                TrueCollection.Add("Mafreidyne ; 004E");
                TrueCollection.Add("Dazzler ; 0050");
                TrueCollection.Add("Nocturnal Flash ; 0051");
                TrueCollection.Add("Pulinpa ; 0052");
                TrueCollection.Add("Tentarafoo ; 0053");
                TrueCollection.Add("Evil Touch ; 0054");
                TrueCollection.Add("Evil Smile ; 0055");
                TrueCollection.Add("Makajama ; 0056");
                TrueCollection.Add("Makajamaon ; 0057");
                TrueCollection.Add("Famine's Breath ; 0058");
                TrueCollection.Add("Famine's Scream ; 0059");
                TrueCollection.Add("Dormina ; 005A");
                TrueCollection.Add("Lullaby ; 005B");
                TrueCollection.Add("Taunt ; 005C");
                TrueCollection.Add("Wage War ; 005D");
                TrueCollection.Add("Ominous Words ; 005E");
                TrueCollection.Add("Abysmal Surge ; 005F");
                TrueCollection.Add("Marin Karin ; 0060");
                TrueCollection.Add("Brain Jack ; 0061");
                TrueCollection.Add("Trapped Rat ; 0062");
                TrueCollection.Add("Self;Destruct(Light) ; 0064");
                TrueCollection.Add("Self;Destruct(Medium) ; 0065");
                TrueCollection.Add("Self;Destruct(Heavy) ; 0066");
                TrueCollection.Add("Life Drain ; 0067");
                TrueCollection.Add("Spirit Drain ; 0068");
                TrueCollection.Add("Life Leech ; 0069");
                TrueCollection.Add("Spirit Leech ; 006A");
                TrueCollection.Add("Foul Breath ; 006E");
                TrueCollection.Add("Stagnant Air ; 006F");
                TrueCollection.Add("Reverse Rub ; 0070");
                TrueCollection.Add("Ghastly Wail ; 0071");
                TrueCollection.Add("Inferno ; 0078");
                TrueCollection.Add("Blazing Hell ; 0079");
                TrueCollection.Add("Low Burn ; 007A");
                TrueCollection.Add("Mid Burn ; 007B");
                TrueCollection.Add("High Burn ; 007C");
                TrueCollection.Add("Low Freeze ; 007D");
                TrueCollection.Add("Mid Freeze ; 007E");
                TrueCollection.Add("High Freeze ; 007F");
                TrueCollection.Add("Low Shock ; 0080");
                TrueCollection.Add("Mid Shock ; 0081");
                TrueCollection.Add("Diamond DUst ; 0082");
                TrueCollection.Add("Ice Age ; 0083");
                TrueCollection.Add("High Shock ; 0084");
                TrueCollection.Add("Low Dizzy ; 0085");
                TrueCollection.Add("Mid Dizzy ; 0086");
                TrueCollection.Add("High Dizzy ; 0087");
                TrueCollection.Add("Low Confuse ; 0088");
                TrueCollection.Add("Mid Confuse ; 0089");
                TrueCollection.Add("High Confuse ; 008A");
                TrueCollection.Add("Low Fear ; 008B");
                TrueCollection.Add("Panta Rhei ; 008C");
                TrueCollection.Add("Vaccum Wave ; 008D");
                TrueCollection.Add("Mid Fear ; 008E");
                TrueCollection.Add("High Fear ; 008F");
                TrueCollection.Add("Low Forget ; 0090");
                TrueCollection.Add("Mid Forget ; 0091");
                TrueCollection.Add("High Forget ; 0092");
                TrueCollection.Add("Low Brainwash ; 0093");
                TrueCollection.Add("Mid Brainwash ; 0094");
                TrueCollection.Add("High Brainwash ; 0095");
                TrueCollection.Add("Thunder Reign ; 0096");
                TrueCollection.Add("Wild Thunder ; 0097");
                TrueCollection.Add("Low Sleep ; 0098");
                TrueCollection.Add("Mid Sleep ; 0099");
                TrueCollection.Add("High Sleep ; 009A");
                TrueCollection.Add("Low Rage ; 009B");
                TrueCollection.Add("Mid Rage ; 009C");
                TrueCollection.Add("High Rage ; 009D");
                TrueCollection.Add("Low Despair ; 009E");
                TrueCollection.Add("Mid Despair ; 009F");
                TrueCollection.Add("Divine Judgment ; 00A0");
                TrueCollection.Add("Samsara ; 00A1");
                TrueCollection.Add("High Despair ; 00A2");
                TrueCollection.Add("Low All Ail ; 00A3");
                TrueCollection.Add("Mid All Ail ; 00A4");
                TrueCollection.Add("High All Ail ; 00A5");
                TrueCollection.Add("Demonic Decree ; 00AA");
                TrueCollection.Add("Die for Me! ; 00AB");
                TrueCollection.Add("Atomic Flare ; 00B0");
                TrueCollection.Add("Cosmic Flare ; 00B1");
                TrueCollection.Add("Black Viper ; 00B4");
                TrueCollection.Add("Morning Star ; 00B5");
                TrueCollection.Add("Psi ; 00BE");
                TrueCollection.Add("Psio ; 00BF");
                TrueCollection.Add("Psiodyne ; 00C0");
                TrueCollection.Add("Mapsi ; 00C1");
                TrueCollection.Add("Mapsio ; 00C2");
                TrueCollection.Add("Mapsiodyne ; 00C3");
                TrueCollection.Add("Psycho Force ; 00C5");
                TrueCollection.Add("Psycho Blast ; 00C6");
                TrueCollection.Add("Lunge ; 00C8");
                TrueCollection.Add("Assault Drive ; 00C9");
                TrueCollection.Add("Megaton Raid ; 00CA");
                TrueCollection.Add("God's Hand ; 00CB");
                TrueCollection.Add("Lunge ; 00CC");
                TrueCollection.Add("Lucky Punch ; 00CD");
                TrueCollection.Add("Miracle Punch ; 00CE");
                TrueCollection.Add("Cleave ; 00D2");
                TrueCollection.Add("Giant Slice ; 00D3");
                TrueCollection.Add("Brave Blade ; 00D4");
                TrueCollection.Add("Sword Dance ; 00D5");
                TrueCollection.Add("Hassou Tobi ; 00D7");
                TrueCollection.Add("Ayamur ; 00D8");
                TrueCollection.Add("Cornered Fang ; 00DC");
                TrueCollection.Add("Rising Slash ; 00DD");
                TrueCollection.Add("Deadly Fury ; 00DE");
                TrueCollection.Add("Snap ; 00E0");
                TrueCollection.Add("Triple Down ; 00E1");
                TrueCollection.Add("One;Shot Kill ; 00E2");
                TrueCollection.Add("Riot Gun ; 00E3");
                TrueCollection.Add("Vajra Blast ; 00E6");
                TrueCollection.Add("Vorpal Blade ; 00E7");
                TrueCollection.Add("Vicious Strike ; 00EB");
                TrueCollection.Add("Heatwave ; 00EC");
                TrueCollection.Add("Gigantomachia ; 00ED");
                TrueCollection.Add("Rampage ; 00F1");
                TrueCollection.Add("Swiftstrike ; 00F2");
                TrueCollection.Add("Deathbound ; 00F3");
                TrueCollection.Add("Agneyastra ; 00F4");
                TrueCollection.Add("Rising Slash(Enemy) ; 00F7");
                TrueCollection.Add("Deadly Fury(Enemy) ; 00F8");
                TrueCollection.Add("Double Fangs ; 00FA");
                TrueCollection.Add("Tempest Slash ; 00FD");
                TrueCollection.Add("Myriad Slashes ; 00FE");
                TrueCollection.Add("Sledgehammer ; 0104");
                TrueCollection.Add("Skull Cracker ; 0105");
                TrueCollection.Add("Terror Claw ; 0106");
                TrueCollection.Add("Headbutt ; 0107");
                TrueCollection.Add("Stomach Blow ; 0108");
                TrueCollection.Add("Dream Needle ; 0109");
                TrueCollection.Add("Hysterical Slap ; 010A");
                TrueCollection.Add("Negative Pile ; 010B");
                TrueCollection.Add("Brain Shake ; 010C");
                TrueCollection.Add("Flash Bomb ; 010E");
                TrueCollection.Add("Mind Slice ; 010F");
                TrueCollection.Add("Bloodbath ; 0110");
                TrueCollection.Add("Memory Blow ; 0111");
                TrueCollection.Add("Insatiable Strike ; 0112");
                TrueCollection.Add("Dormin Rush ; 0113");
                TrueCollection.Add("Oni;Kagura ; 0114");
                TrueCollection.Add("Bad Beat ; 0115");
                TrueCollection.Add("Drain Buster ; 0116");
                TrueCollection.Add("Handgun(MC Gun) ; 0118");
                TrueCollection.Add("Shotgun(Skull Gun) ; 0119");
                TrueCollection.Add("Slingshot(Mora Gun) ; 011A");
                TrueCollection.Add("Machine Gun(Panther Gun) ; 011B");
                TrueCollection.Add("Assault Riffle ; 011C");
                TrueCollection.Add("Revolver ; 011D");
                TrueCollection.Add("Grenade Launcher ; 011E");
                TrueCollection.Add("Laser Gun ; 011F");
                TrueCollection.Add("Attack(Normal Attack) ; 012B");
                TrueCollection.Add("Dia ; 012C");
                TrueCollection.Add("Diarama ; 012D");
                TrueCollection.Add("Diarahan ; 012E");
                TrueCollection.Add("Media ; 0131");
                TrueCollection.Add("Mediarama ; 0132");
                TrueCollection.Add("Mediarahan ; 0133");
                TrueCollection.Add("Recarm ; 0136");
                TrueCollection.Add("Samarecarm ; 0137");
                TrueCollection.Add("Recarmdra ; 0138");
                TrueCollection.Add("Amrita Drop ; 013B");
                TrueCollection.Add("Amrita Shower ; 013C");
                TrueCollection.Add("Salvation ; 013E");
                TrueCollection.Add("Patra ; 0145");
                TrueCollection.Add("Energy Shower ; 0147");
                TrueCollection.Add("Energy Drop ; 0148");
                TrueCollection.Add("Baisudi ; 0149");
                TrueCollection.Add("Me Patra ; 014A");
                TrueCollection.Add("Mabaisudi ; 014B");
                TrueCollection.Add("Tarukaja ; 014F");
                TrueCollection.Add("Rakukaja ; 0150");
                TrueCollection.Add("Sukukaja ; 0151");
                TrueCollection.Add("Heat Riser ; 0152");
                TrueCollection.Add("Matarukaja ; 0154");
                TrueCollection.Add("Marakukaja ; 0155");
                TrueCollection.Add("Masukukaja ; 0156");
                TrueCollection.Add("Thermopylae ; 0157");
                TrueCollection.Add("Tarunda ; 0159");
                TrueCollection.Add("Rakunda ; 015A");
                TrueCollection.Add("Sukunda ; 015B");
                TrueCollection.Add("Debilitate ; 015C");
                TrueCollection.Add("Matarunda ; 015E");
                TrueCollection.Add("Marakunda ; 015F");
                TrueCollection.Add("Masukunda ; 0160");
                TrueCollection.Add("Dekunda ; 0163");
                TrueCollection.Add("Dekaja ; 0164");
                TrueCollection.Add("Charge ; 0168");
                TrueCollection.Add("Concentrate ; 0169");
                TrueCollection.Add("Rebellion ; 016D");
                TrueCollection.Add("Revolution ; 016E");
                TrueCollection.Add("Tetrakarn ; 0172");
                TrueCollection.Add("Makarakarn ; 0173");
                TrueCollection.Add("Tetraja ; 0174");
                TrueCollection.Add("Tetra Break ; 0177");
                TrueCollection.Add("Makara Break ; 0178");
                TrueCollection.Add("Fire Wall ; 017C");
                TrueCollection.Add("Ice Wall ; 017D");
                TrueCollection.Add("Elec Wall ; 017E");
                TrueCollection.Add("Wind Wall ; 017F");
                TrueCollection.Add("Fire Break ; 0181");
                TrueCollection.Add("Ice Break ; 0182");
                TrueCollection.Add("Wind Break ; 0183");
                TrueCollection.Add("Elec Break ; 0184");
                TrueCollection.Add("Trafuri(Escape 100% from Battles) ; 0186");
                TrueCollection.Add("Traesto(Teleport to Dungeon Entrance) ; 0187");
                TrueCollection.Add("Nuke Wall ; 0189");
                TrueCollection.Add("Psy Wall ; 018A");
                TrueCollection.Add("Nuke Break ; 018B");
                TrueCollection.Add("Psy Break ; 018C");
                TrueCollection.Add("All;Out Lv1 ; 0190");
                TrueCollection.Add("All;Out Lv2 ; 0191");
                TrueCollection.Add("All;Out Lv3 ; 0192");
                TrueCollection.Add("Emergency Escape ; 0193");
                TrueCollection.Add("Attack ; 0194");
                TrueCollection.Add("Down Shot ; 0195");
                TrueCollection.Add("Summon ; 0196");
                TrueCollection.Add("Call for Backup ; 0197");
                TrueCollection.Add("Outlaw Attack ; 0198");
                TrueCollection.Add("Barrage ; 0199");
                TrueCollection.Add("Follow Crush ; 019A");
                TrueCollection.Add("Follow Claw ; 019B");
                TrueCollection.Add("Follow Whip ; 019C");
                TrueCollection.Add("Follow Blade ; 019D");
                TrueCollection.Add("Follow Knuckle ; 019E");
                TrueCollection.Add("Follow Axe ; 019F");
                TrueCollection.Add("Follow Saber ; 01A0");
                TrueCollection.Add("Dispose Item ; 01A1");
                TrueCollection.Add("Heal Enemy ; 01A2");
                TrueCollection.Add("Death(Despair) ; 01A3");
                TrueCollection.Add("Ally1 Follow;Up ; 01A4");
                TrueCollection.Add("Ally2 Follow;Up ; 01A5");
                TrueCollection.Add("Ally3 Follow;Up ; 01A6");
                TrueCollection.Add("Ally4 Follow;Up ; 01A7");
                TrueCollection.Add("Ally5 Follow;Up ; 01A8");
                TrueCollection.Add("Ally6 Follow;Up ; 01A9");
                TrueCollection.Add("Ally7 Follow;Up ; 01AA");
                TrueCollection.Add("Power Up Enemy ; 01AB");
                TrueCollection.Add("Power Up Enemy ; 01AC");
                TrueCollection.Add("Power Up Enemy ; 01AD");
                TrueCollection.Add("Steal Info ; 01AE");
                TrueCollection.Add("Sup Matarukaja ; 01AF");
                TrueCollection.Add("Sup Marakukaja ; 01B0");
                TrueCollection.Add("Sup Masukukaja ; 01B1");
                TrueCollection.Add("Sup All Kaja ; 01B2");
                TrueCollection.Add("Sup Charge ; 01B3");
                TrueCollection.Add("Sup Hp+30% ; 01B4");
                TrueCollection.Add("Sup Sp+10% ; 01B5");
                TrueCollection.Add("Sup Escape Route ; 01B6");
                TrueCollection.Add("Sup Third Eye ; 01B7");
                TrueCollection.Add("Subrecover HP ; 01B8");
                TrueCollection.Add("Subrecover SP ; 01B9");
                TrueCollection.Add("Analysis ; 01BA");
                TrueCollection.Add("Deep Analysis ; 01BB");
                TrueCollection.Add("Full Analysis ; 01BC");
                TrueCollection.Add("All;Out Attack ; 01BD");
                TrueCollection.Add("Dust Flurry ; 01BE");
                TrueCollection.Add("Tongue Whip ; 01BF");
                TrueCollection.Add("Whip Strike ; 01C0");
                TrueCollection.Add("Lustful Slurp ; 01C1");
                TrueCollection.Add("Libido Boost ; 01C2");
                TrueCollection.Add("Golden Knife ; 01C3");
                TrueCollection.Add("Lick ; 01C4");
                TrueCollection.Add("Gold Medal Spike ; 01C5");
                TrueCollection.Add("Volleyball Assault ; 01C6");
                TrueCollection.Add("Maelstrom ; 01C7");
                TrueCollection.Add("Flame Dance ; 01C8");
                TrueCollection.Add("Silent Snowscape ; 01C9");
                TrueCollection.Add("Thunderclap ; 01CA");
                TrueCollection.Add("Maeiga ; 01CB");
                TrueCollection.Add("Hunger All ; 01CC");
                TrueCollection.Add("Ocular Vulcan ; 01CD");
                TrueCollection.Add("Missile Part ; 01CE");
                TrueCollection.Add("Fear Gas ; 01CF");
                TrueCollection.Add("Super VIP Form ; 01D0");
                TrueCollection.Add("March of the Piggy ; 01D1");
                TrueCollection.Add("Sphinx Swipe ; 01D2");
                TrueCollection.Add("Wing Blast ; 01D3");
                TrueCollection.Add("Rapid Ascent ; 01D4");
                TrueCollection.Add("Sphinx Dive ; 01D5");
                TrueCollection.Add("Dreadful Scream ; 01D6");
                TrueCollection.Add("Bite ; 01D7");
                TrueCollection.Add("Restore ; 01D8");
                TrueCollection.Add("The Artist's Grace ; 01D9");
                TrueCollection.Add("Work Order ; 01DA");
                TrueCollection.Add("Sacrifice Order ; 01DB");
                TrueCollection.Add("Selfless Devotion ; 01DC");
                TrueCollection.Add("Penalty ; 01DD");
                TrueCollection.Add("Coin Attack ; 01DE");
                TrueCollection.Add("Severing Slash ; 01DF");
                TrueCollection.Add("Gatling Gun ; 01E0");
                TrueCollection.Add("Berserker Dance ; 01E1");
                TrueCollection.Add("Roulette:HP ; 01E2");
                TrueCollection.Add("Roulette:SP ; 01E3");
                TrueCollection.Add("Roulette:Money ; 01E4");
                TrueCollection.Add("Roulette:Aid 1 ; 01E5");
                TrueCollection.Add("Roulette:Aid 2 ; 01E6");
                TrueCollection.Add("Roulette:Aid 3 ; 01E7");
                TrueCollection.Add("Beast King's Wrath ; 01E8");
                TrueCollection.Add("Hunting Stance ; 01E9");
                TrueCollection.Add("Arm of Destrtuction ; 01EA");
                TrueCollection.Add("Gryphon's Breath ; 01EB");
                TrueCollection.Add("Royal Wing Beam ; 01EC");
                TrueCollection.Add("Cannon Fire ; 01ED");
                TrueCollection.Add("Cannon Barage ; 01EE");
                TrueCollection.Add("Unholy Convergence ; 01EF");
                TrueCollection.Add("Pyramid Blast ; 01F0");
                TrueCollection.Add("Tyrant's Fist ; 01F1");
                TrueCollection.Add("Tyrant's Glare ; 01F2");
                TrueCollection.Add("Tyrant's Wave ; 01F3");
                TrueCollection.Add("Fig Seed ; 01F4");
                TrueCollection.Add("Medicine ; 01F5");
                TrueCollection.Add("Ointment ; 01F6");
                TrueCollection.Add("Antibiotic Gel ; 01F7");
                TrueCollection.Add("Life Stone ; 01F8");
                TrueCollection.Add("Bead ; 01F9");
                TrueCollection.Add("Value Medicine ; 01FA");
                TrueCollection.Add("Medical Kit ; 01FB");
                TrueCollection.Add("Maka Leaf ; 01FC");
                TrueCollection.Add("Bead Chain ; 01FD");
                TrueCollection.Add("Soul Drop ; 01FE");
                TrueCollection.Add("Snuff Soul ; 01FF");
                TrueCollection.Add("Chewing Soul ; 0200");
                TrueCollection.Add("Soul Food ; 0201");
                TrueCollection.Add("Revival Bead ; 0202");
                TrueCollection.Add("Balm of Life ; 0203");
                TrueCollection.Add("Royel Jelly ; 0204");
                TrueCollection.Add("Organic Herb ; 0205");
                TrueCollection.Add("Disclose ; 0206");
                TrueCollection.Add("Tranquilizer ; 0207");
                TrueCollection.Add("Kopi Luwak ; 0208");
                TrueCollection.Add("Goho;M ; 0209");
                TrueCollection.Add("Vanish Ball ; 020A");
                TrueCollection.Add("Soma ; 020B");
                TrueCollection.Add("Amrita Soda ; 020C");
                TrueCollection.Add("Hyrania ; 020D");
                TrueCollection.Add("Muscle Drink ; 020E");
                TrueCollection.Add("Odd Morsel ; 020F");
                TrueCollection.Add("Rancid Gravy ; 0210");
                TrueCollection.Add("Plume of Dusk ; 0211");
                TrueCollection.Add("Magic Mirror ; 0212");
                TrueCollection.Add("Physical Mirror ; 0213");
                TrueCollection.Add("Universe Ring ; 0214");
                TrueCollection.Add("Sleipnir ; 0215");
                TrueCollection.Add("Obsidiam Mirror ; 0216");
                TrueCollection.Add("Puryfing Water ; 0217");
                TrueCollection.Add("Puryfing Salt ; 0218");
                TrueCollection.Add("Firecracker ; 0219");
                TrueCollection.Add("Twins Down Attack ; 0258");
                TrueCollection.Add("Caro Rod ; 0259");
                TrueCollection.Add("Caro Attack ; 025A");
                TrueCollection.Add("Megidolaon ; 025B");
                TrueCollection.Add("Rays of Control ; 025C");
                TrueCollection.Add("Rays of Control ; 025D");
                TrueCollection.Add("Rays of Control ; 025E");
                TrueCollection.Add("Rays of Control ; 025F");
                TrueCollection.Add("Arrow of Light ; 0260");
                TrueCollection.Add("Diffraction Arrow ; 0261");
                TrueCollection.Add("Light Edge ; 0262");
                TrueCollection.Add("Gathering Light ; 0263");
                TrueCollection.Add("Eternal Light ; 0264");
                TrueCollection.Add("Holy Change ; 0265");
                TrueCollection.Add("Distortion Wave ; 0266");
                TrueCollection.Add("Though Law ; 0267");
                TrueCollection.Add("Frail Law ; 0268");
                TrueCollection.Add("New Creation ; 0269");
                TrueCollection.Add("Distortion Surge ; 026A");
                TrueCollection.Add("Arrow of Light ; 026B");
                TrueCollection.Add("Manifest Sword ; 026C");
                TrueCollection.Add("Manifest Gun ; 026D");
                TrueCollection.Add("Manifest Bell ; 026E");
                TrueCollection.Add("Sword of Judgement ; 026F");
                TrueCollection.Add("Capital Punishment ; 0270");
                TrueCollection.Add("Manifest Book ; 0271");
                TrueCollection.Add("Distorted Lust ; 0272");
                TrueCollection.Add("Gospel ; 0273");
                TrueCollection.Add("Distorted Wrath ; 0274");
                TrueCollection.Add("Distorted Vanity ; 0275");
                TrueCollection.Add("Song of Salvation ; 0276");
                TrueCollection.Add("Wrath of God ; 0277");
                TrueCollection.Add("Distorted Gluttony ; 0278");
                TrueCollection.Add("Distorted Envy ; 0279");
                TrueCollection.Add("Song of Placation ; 027A");
                TrueCollection.Add("Divine Apex ; 027B");
                TrueCollection.Add("Rays of Control ; 027C");
                TrueCollection.Add("Distorted Avarice ; 027D");
                TrueCollection.Add("Will of the People ; 027E");
                TrueCollection.Add("Rays of Control ; 027F");
                TrueCollection.Add("Moral Support ; 0280");
                TrueCollection.Add("Active Support ; 0281");
                TrueCollection.Add("Mental Hack ; 0282");
                TrueCollection.Add("Emergency Shift ; 0283");
                TrueCollection.Add("Final Guard ; 0284");
                TrueCollection.Add("Position Hack ; 0285");
                TrueCollection.Add("High Analyze ; 0286");
                TrueCollection.Add("Treasure Skimmer ; 0287");
                TrueCollection.Add("Subrecover HP EX ; 0288");
                TrueCollection.Add("Subrecover SP EX ; 0289");
                TrueCollection.Add("Big Bang Order ; 028E");
                TrueCollection.Add("Roulette Time ; 028F");
                TrueCollection.Add("Trip;Upper ; 0290");
                TrueCollection.Add("Lust Sphere ; 0291");
                TrueCollection.Add("Down Shot 2 ; 0292");
                TrueCollection.Add("Down Shot 3 ; 0293");
                TrueCollection.Add("Down Shot 4 ; 0294");
                TrueCollection.Add("Ekectro Attack ; 0295");
                TrueCollection.Add("Sinful Shell ; 0296");
                TrueCollection.Add("Follow Black ; 0297");
                TrueCollection.Add("Madara;Megido ; 0299");
                TrueCollection.Add("Curry Raku ; 029A");
                TrueCollection.Add("Enemy Benefit ; 029B");
                TrueCollection.Add("Diarahan ; 029C");
                TrueCollection.Add("Curry Suku ; 029D");
                TrueCollection.Add("Decoy Ball ; 029E");
                TrueCollection.Add("Super Decoy Ball ; 029F");
                TrueCollection.Add("Metabolic Wave ; 02A0");
                TrueCollection.Add("Laevateinn ; 02A1");
                TrueCollection.Add("Desperation ; 02A2");
                TrueCollection.Add("Call of Chaos ; 02A3");
                TrueCollection.Add("Big Bang Challenge ; 02A4");
                TrueCollection.Add("Grail Light 2 ; 02A5");
                TrueCollection.Add("Megidola ; 02A6");
                TrueCollection.Add("Rage Transmission ; 02A7");
                TrueCollection.Add("Hundred Slaps ; 02A8");
                TrueCollection.Add("Distorted Pride ; 02A9");
                TrueCollection.Add("Divine Punishment ; 02AA");
                TrueCollection.Add("Will of the People ; 02AB");
                TrueCollection.Add("Wind Cutter ; 02AC");
                TrueCollection.Add("Shoot Up ; 02AD");
                TrueCollection.Add("Executive Punch ; 02AE");
                TrueCollection.Add("Magidolaon ; 02AF");
                TrueCollection.Add("Vorpal Blade ; 02B0");
                TrueCollection.Add("Megidolaon ; 02B1");
                TrueCollection.Add("Big Bang Burger ; 02B2");
                TrueCollection.Add("Earth Burger ; 02B3");
                TrueCollection.Add("Mars Burger ; 02B4");
                TrueCollection.Add("Moon Burger ; 02B5");
                TrueCollection.Add("Saturn Burger ; 02B6");
                TrueCollection.Add("Justine Attack ; 02B7");
                TrueCollection.Add("Caroline Attack ; 02B8");
                TrueCollection.Add("Curry Makara ; 02B9");
                TrueCollection.Add("Curry Tetra ; 02BA");
                TrueCollection.Add("Curry Endure ; 02BB");
                TrueCollection.Add("Curry Charge ; 02BC");
                TrueCollection.Add("Curry Concentration ; 02BD");
                TrueCollection.Add("Curry Heat Riser ; 02BE");
                TrueCollection.Add("Cadenza ; 02C0");
                TrueCollection.Add("Cross Slash ; 02C1");
                TrueCollection.Add("Door To Hades ; 02C2");
                TrueCollection.Add("Magatsu Mandala ; 02C3");
                TrueCollection.Add("Shining Arrows ; 02C4");
                TrueCollection.Add("Beast Weaver ; 02C5");
                TrueCollection.Add("Titanomachia ; 02C6");
                TrueCollection.Add("Abyssal Wings ; 02C7");
                TrueCollection.Add("Oratario ; 02C8");
                TrueCollection.Add("Megido ; 02D0");
                TrueCollection.Add("Megidola ; 02D1");
                TrueCollection.Add("Megidolaon ; 02D2");
                TrueCollection.Add("Slam ; 02D3");
                TrueCollection.Add("Megaton Raid ; 02D4");
                TrueCollection.Add("One;Shot Kill ; 02D5");
                TrueCollection.Add("Inferno ; 02D6");
                TrueCollection.Add("Diamond Dust ; 02D7");
                TrueCollection.Add("Curry 1 ; 02DA");
                TrueCollection.Add("Curry 2 ; 02DB");
                TrueCollection.Add("Reviv;All ; 02DC");
                TrueCollection.Add("Reviv;All Z ; 02DD");
                TrueCollection.Add("Wild Talk ; 02E0");
                TrueCollection.Add("Baton Pass ; 02E1");
                TrueCollection.Add("Punk Talk ; 02E2");
                TrueCollection.Add("Pickpocket ; 02E3");
                TrueCollection.Add("Harisen Recovery ; 02E4");
                TrueCollection.Add("Protect ; 02E5");
                TrueCollection.Add("Girl Talk ; 02E6");
                TrueCollection.Add("Crocodile Tears ; 02E7");
                TrueCollection.Add("Sexy Technique ; 02E8");
                TrueCollection.Add("Detective Talk ; 02E9");
                TrueCollection.Add("Artist Talk ; 02EA");
                TrueCollection.Add("Negotiating ; 02EB");
                TrueCollection.Add("Fundraising ; 02EC");
                TrueCollection.Add("Manipulation ; 02ED");
                TrueCollection.Add("Mind Control ; 02EE");
                TrueCollection.Add("Charisma Speech ; 02EF");
                TrueCollection.Add("Brainiac Talk ; 02F0");
                TrueCollection.Add("Sabaki ; 02F1");
                TrueCollection.Add("Kakoi Kuzushi ; 02F2");
                TrueCollection.Add("Touryou ; 02F3");
                TrueCollection.Add("Togo System ; 02F4");
                TrueCollection.Add("Bullet Hail ; 02F5");
                TrueCollection.Add("Warning Shot ; 02F6");
                TrueCollection.Add("Celeb Talk ; 02F7");
                TrueCollection.Add("Kitty Talk ; 02F8");
                TrueCollection.Add("Brave Blade ; 0300");
                TrueCollection.Add("Assault Dive ; 0301");
                TrueCollection.Add("Terror Claw ; 0302");
                TrueCollection.Add("Bufudyne ; 0303");
                TrueCollection.Add("Psiodyne ; 0304");
                TrueCollection.Add("Mazionga ; 0305");
                TrueCollection.Add("Maziodyne ; 0306");
                TrueCollection.Add("Maeiga ; 0307");
                TrueCollection.Add("Maeigaon ; 0308");
                TrueCollection.Add("Counter ; 0320");
                TrueCollection.Add("Counterstrike ; 0321");
                TrueCollection.Add("High Counter ; 0322");
                TrueCollection.Add("Endure ; 0325");
                TrueCollection.Add("Enduring Soul ; 0326");
                TrueCollection.Add("Survival Trick ; 0329");
                TrueCollection.Add("Dodge Fire ; 032A");
                TrueCollection.Add("Evade Fire ; 032B");
                TrueCollection.Add("Dodge Ice ; 032C");
                TrueCollection.Add("Evade Ice ; 032D");
                TrueCollection.Add("Dodge Wind ; 032E");
                TrueCollection.Add("Evade Wind ; 032F");
                TrueCollection.Add("Dodge Elec ; 0330");
                TrueCollection.Add("Evade Elec ; 0331");
                TrueCollection.Add("Dodge Phys ; 0332");
                TrueCollection.Add("Evade Phys ; 0333");
                TrueCollection.Add("Fire Boost ; 0334");
                TrueCollection.Add("Fire Amp ; 0335");
                TrueCollection.Add("Ice Boost ; 0336");
                TrueCollection.Add("Ice Amp ; 0337");
                TrueCollection.Add("Wind Boost ; 0338");
                TrueCollection.Add("Wind Amp ; 0339");
                TrueCollection.Add("Elec Boost ; 033A");
                TrueCollection.Add("Elect Amp ; 033B");
                TrueCollection.Add("Angelic Grace ; 033C");
                TrueCollection.Add("Divine Grace ; 033D");
                TrueCollection.Add("Regenerate 1 ; 033E");
                TrueCollection.Add("Regenerate 2 ; 033F");
                TrueCollection.Add("Regenerate 3 ; 0340");
                TrueCollection.Add("Dodge Bless ; 0341");
                TrueCollection.Add("Dodge Curse ; 0342");
                TrueCollection.Add("Invigorate 1 ; 0343");
                TrueCollection.Add("Invogorate 2 ; 0344");
                TrueCollection.Add("Invigorate 3 ; 0345");
                TrueCollection.Add("Evade Bless ; 0346");
                TrueCollection.Add("Evade Curse ; 0347");
                TrueCollection.Add("Attack Master ; 0348");
                TrueCollection.Add("Auto;Mataru ; 0349");
                TrueCollection.Add("Defense Master ; 034B");
                TrueCollection.Add("Auto;Maraku ; 034C");
                TrueCollection.Add("Speed Master ; 034E");
                TrueCollection.Add("Auto;Masuko ; 034F");
                TrueCollection.Add("Fast Heal ; 0352");
                TrueCollection.Add("Insta;Heal ; 0353");
                TrueCollection.Add("Arms Master ; 0354");
                TrueCollection.Add("Spell Master ; 0355");
                TrueCollection.Add("Sharp Student ; 0357");
                TrueCollection.Add("Apt Pupil ; 0358");
                TrueCollection.Add("Ali Dance ; 0359");
                TrueCollection.Add("Firm Stance ; 035A");
                TrueCollection.Add("Life Aid ; 035C");
                TrueCollection.Add("Victory Cry ; 035D");
                TrueCollection.Add("Growth 1 ; 035E");
                TrueCollection.Add("Growth 2 ; 035F");
                TrueCollection.Add("Growth 3 ; 0360");
                TrueCollection.Add("Unshaken Will ; 0361");
                TrueCollection.Add("Baton Pass ; 0363");
                TrueCollection.Add("Soul Touch ; 0364");
                TrueCollection.Add("Kakoi Kuzushi ; 0365");
                TrueCollection.Add("Resist Fire ; 0366");
                TrueCollection.Add("Null Fire ; 0367");
                TrueCollection.Add("Repel Fire ; 0368");
                TrueCollection.Add("Drain Fire ; 0369");
                TrueCollection.Add("Resist Ice ; 036B");
                TrueCollection.Add("Null Ice ; 036C");
                TrueCollection.Add("Repel Ice ; 036D");
                TrueCollection.Add("Drain Ice ; 036E");
                TrueCollection.Add("Resist Wind ; 0370");
                TrueCollection.Add("Null Wind ; 0371");
                TrueCollection.Add("Repel Wind ; 0372");
                TrueCollection.Add("Drain Wind ; 0373");
                TrueCollection.Add("Resist Elec ; 0375");
                TrueCollection.Add("Null Elec ; 0376");
                TrueCollection.Add("Repel Elec ; 0377");
                TrueCollection.Add("Drain Elec ; 0378");
                TrueCollection.Add("Resist Bless ; 037A");
                TrueCollection.Add("Null Bless ; 037B");
                TrueCollection.Add("Repel Bless ; 037C");
                TrueCollection.Add("Drain Bless ; 037D");
                TrueCollection.Add("Resist Curse ; 037F");
                TrueCollection.Add("Null Curse ; 0380");
                TrueCollection.Add("Repel Curse ; 0381");
                TrueCollection.Add("Drain Curse ; 0382");
                TrueCollection.Add("Resist Phys ; 0384");
                TrueCollection.Add("Null Phys ; 0385");
                TrueCollection.Add("Repel Phys ; 0386");
                TrueCollection.Add("Drain Phys ; 0387");
                TrueCollection.Add("Ailment Boost ; 0389");
                TrueCollection.Add("Hama Boost ; 038A");
                TrueCollection.Add("Mudo Boost ; 038B");
                TrueCollection.Add("Dizzy Boost ; 038E");
                TrueCollection.Add("Confuse Boost ; 038F");
                TrueCollection.Add("Fear Boost ; 0390");
                TrueCollection.Add("Forget Boost ; 0391");
                TrueCollection.Add("Sleep Boost ; 0392");
                TrueCollection.Add("Rage Boost ; 0393");
                TrueCollection.Add("Despair Boost ; 0394");
                TrueCollection.Add("Brainwash Boost ; 0396");
                TrueCollection.Add("Resist Dizzy ; 0398");
                TrueCollection.Add("Resist Confuse ; 0399");
                TrueCollection.Add("Resist Fear ; 039A");
                TrueCollection.Add("Resist Forget ; 039B");
                TrueCollection.Add("Resist Sleep ; 039C");
                TrueCollection.Add("Resist Rage ; 039D");
                TrueCollection.Add("Resist Despair ; 039E");
                TrueCollection.Add("Resist Brainwash ; 03A0");
                TrueCollection.Add("Null Dizzy ; 03A2");
                TrueCollection.Add("Null Confuse ; 03A3");
                TrueCollection.Add("Null Fear ; 03A4");
                TrueCollection.Add("Null Forget ; 03A5");
                TrueCollection.Add("Null Sleep ; 03A6");
                TrueCollection.Add("Null Rage ; 03A7");
                TrueCollection.Add("Null Despair ; 03A8");
                TrueCollection.Add("Null Brainwash ; 03AA");
                TrueCollection.Add("Burn Boost ; 03AC");
                TrueCollection.Add("Freeze Boost ; 03AD");
                TrueCollection.Add("Shock Boost ; 03AE");
                TrueCollection.Add("Fortified Moxy ; 03B0");
                TrueCollection.Add("Adverse Resolve ; 03B1");
                TrueCollection.Add("Last Stand ; 03B2");
                TrueCollection.Add("Heat Up ; 03B3");
                TrueCollection.Add("Touch n' Go ; 03B5");
                TrueCollection.Add("Climate Decorum ; 03B6");
                TrueCollection.Add("Ambient Aid ; 03B7");
                TrueCollection.Add("Snipe ; 03B9");
                TrueCollection.Add("Cripple ; 03BA");
                TrueCollection.Add("Trigger Happy ; 03BB");
                TrueCollection.Add("Resist Nuke ; 03BC");
                TrueCollection.Add("Null Nuke ; 03BD");
                TrueCollection.Add("Repel Nuke ; 03BE");
                TrueCollection.Add("Drain Nuke ; 03BF");
                TrueCollection.Add("Resist Psy ; 03C1");
                TrueCollection.Add("Null Psy ; 03C2");
                TrueCollection.Add("Repel Psy ; 03C3");
                TrueCollection.Add("Drain Psy ; 03C4");
                TrueCollection.Add("Nuke Boost ; 03C6");
                TrueCollection.Add("Nuke Amp ; 03C7");
                TrueCollection.Add("Psy Boost ; 03C9");
                TrueCollection.Add("Psy Amp ; 03CA");
                TrueCollection.Add("Dodge Nuke ; 03CC");
                TrueCollection.Add("Evade Nuke ; 03CD");
                TrueCollection.Add("Dodge Psy ; 03CF");
                TrueCollection.Add("Evade Psy ; 03D0");
                TrueCollection.Add("Reserve ; 03D1");
                TrueCollection.Add("Bless Boost ; 03D2");
                TrueCollection.Add("Bless Amp ; 03D3");
                TrueCollection.Add("Reserve ; 03D4");
                TrueCollection.Add("Curse Boost ; 03D5");
                TrueCollection.Add("Curse Amp ; 03D6");
                TrueCollection.Add("Reserve ; 03D7");
                TrueCollection.Add("Magic Ability ; 03D8");
                TrueCollection.Add("Fortify Spirit ; 03D9");
                TrueCollection.Add("Almighty Boost ; 03DA");
                TrueCollection.Add("Almighty Amp ; 03DB");
                TrueCollection.Add("Zenith Defense ; 03DC");
                TrueCollection.Add("Soul Chain ; 03DE");
                TrueCollection.Add("Vanity Copy ; 03DF");
                TrueCollection.Add("Gluttonous Snuff ; 03E0");
                TrueCollection.Add("Slot Defense ; 03E1");
            }

            foreach (object item in TrueCollection)
                listBox.Items.Add(item);

            LastCollection = TrueCollection;
        }
    }
}
